#!/usr/bin/env bash
# Obscura47 - dedicated relay node setup (VPS-2).
#
# RUN-IN-PLACE: run from inside the checkout you cloned. Configures *this*
# checkout; no second clone to a hardcoded path. This box runs only the relay
# node and points at an existing registry - no registry, no exit.
#
#   git clone https://github.com/SBertrand-47/Obscura47.git
#   cd Obscura47
#   sudo bash scripts/vps-node-setup.sh
#
# Guided + automatic: detects your public IP, opens the firewall, installs+
# starts the node, then verifies the registry sees it AND that its ws_port is
# reachable from the public internet (the #1 thing that breaks a relay).
set -euo pipefail

SCRIPT_SRC="${BASH_SOURCE[0]}"
# shellcheck source=scripts/lib/common.sh
source "$(cd "$(dirname "$(readlink -f "$SCRIPT_SRC")")" && pwd)/lib/common.sh"

APP_DIR="$(oc_app_dir "$SCRIPT_SRC")"
DATA_DIR="${OBSCURA_DATA_DIR:-/var/lib/obscura47}"
NODE_PORT=5001; NODE_WS_PORT=5002

oc_require_root "scripts/vps-node-setup.sh"
echo "=== Obscura47 Relay Node Setup ==="
oc_log "Install dir (run-in-place): $APP_DIR"

[ -f "$APP_DIR/join_network.py" ] || oc_die "join_network.py not found in $APP_DIR - run this from inside the checkout."

# 1. venv + deps
oc_setup_venv "$APP_DIR"

# 2. writable state
mkdir -p "$DATA_DIR/logs"

# 3. service user
read -r RUN_USER RUN_GROUP <<<"$(oc_pick_run_user "$APP_DIR" "$DATA_DIR")"
chown -R "$RUN_USER:$RUN_GROUP" "$DATA_DIR"

# 4. which registry to join
DEFAULT_REG_URL="${OBSCURA_REGISTRY_URL:-https://db.monmedjs.com}"
REGISTRY_URL="$(oc_ask "Registry URL to join" "$DEFAULT_REG_URL")"
PUBLIC_IP="$(oc_detect_public_ip "$REGISTRY_URL")"
oc_log "Detected public IP: ${PUBLIC_IP:-<unknown>}  (peers must be able to reach this)"

# 5. node-only .env (only if absent)
if [ ! -f "$APP_DIR/.env" ]; then
    cat > "$APP_DIR/.env" <<ENVEOF
# Obscura47 Relay Node configuration (generated by vps-node-setup.sh)
OBSCURA_REGISTRY_URL=${REGISTRY_URL}

# Relay listen ports - MUST be reachable from the public internet.
OBSCURA_NODE_LISTEN_PORT=${NODE_PORT}
OBSCURA_NODE_WS_PORT=${NODE_WS_PORT}

# Writable paths (under ${DATA_DIR} for the hardened unit's ReadWritePaths)
OBSCURA_NODE_KEY_PATH=${DATA_DIR}/node_key.pem
OBSCURA_LOG_DIR=${DATA_DIR}/logs
ENVEOF
    chown "$RUN_USER:$RUN_GROUP" "$APP_DIR/.env"
    chmod 600 "$APP_DIR/.env"
    oc_log "Created node .env (defaults work out of the box)"
else
    oc_step ".env already exists - leaving it untouched"
fi

# 6. systemd unit
oc_render_unit "$APP_DIR/scripts/obscura47-node.service.template" \
    "obscura47-node.service" "$APP_DIR" "$RUN_USER" "$RUN_GROUP" "$DATA_DIR" "join_network.py node"
systemctl enable obscura47-node >/dev/null 2>&1 || true

# 7. firewall - a relay is useless if its ports aren't reachable
if oc_confirm "Open firewall for node ports ($NODE_PORT, $NODE_WS_PORT)?"; then
    oc_open_firewall "$NODE_PORT" "$NODE_WS_PORT" || true
fi

# 8. start + verify (registration + external ws_port reachability)
oc_step "Starting obscura47-node..."
systemctl restart obscura47-node
sleep 4
if systemctl is-active --quiet obscura47-node; then
    oc_log "Service is active"
else
    oc_err "Service failed to start - check: journalctl -u obscura47-node -e"
fi
oc_verify "$APP_DIR" "node" "$NODE_WS_PORT"

echo
echo "=== Setup complete ==="
echo "  Service: systemctl status obscura47-node   Logs: journalctl -u obscura47-node -f"
echo "  Joined registry: $REGISTRY_URL"
echo "  Confirm it's listed:  curl -s ${REGISTRY_URL%/}/peers | grep \"${PUBLIC_IP:-<your-ip>}\""
echo
