#!/usr/bin/env bash
# Obscura47 - registry + exit box setup (VPS-1).
#
# RUN-IN-PLACE: run this from inside the checkout you cloned. It configures
# *this* checkout - it does not clone a second copy to a hardcoded path, so the
# running service can never diverge from the code you're looking at.
#
#   git clone https://github.com/SBertrand-47/Obscura47.git
#   cd Obscura47
#   sudo bash scripts/vps-setup.sh
#
# Guided + automatic: detects your public IP, generates a strong admin key,
# opens the firewall, installs+starts the service, then verifies reachability.
# You only need to touch .env for non-default customization.
set -euo pipefail

SCRIPT_SRC="${BASH_SOURCE[0]}"
# shellcheck source=scripts/lib/common.sh
source "$(cd "$(dirname "$(readlink -f "$SCRIPT_SRC")")" && pwd)/lib/common.sh"

APP_DIR="$(oc_app_dir "$SCRIPT_SRC")"
DATA_DIR="${OBSCURA_DATA_DIR:-/var/lib/obscura47}"
EXIT_PORT=6000; EXIT_WS_PORT=6001; REGISTRY_PORT=8470

oc_require_root "scripts/vps-setup.sh"
echo "=== Obscura47 Registry + Exit Setup ==="
oc_log "Install dir (run-in-place): $APP_DIR"

[ -f "$APP_DIR/server.py" ] || oc_die "server.py not found in $APP_DIR - run this from inside the checkout."

# 1. venv + deps
oc_setup_venv "$APP_DIR"

# 2. writable state dirs
mkdir -p "$DATA_DIR/audit" "$DATA_DIR/logs"

# 3. decide service user (prefers hardened 'obscura'; falls back to owner)
read -r RUN_USER RUN_GROUP <<<"$(oc_pick_run_user "$APP_DIR" "$DATA_DIR")"
chown -R "$RUN_USER:$RUN_GROUP" "$DATA_DIR"

# 4. public IP + registry URL (this box fronts its own registry)
PUBLIC_IP="$(oc_detect_public_ip)"
oc_log "Detected public IP: ${PUBLIC_IP:-<unknown>}"
DEFAULT_REG_URL="${OBSCURA_REGISTRY_URL:-https://db.monmedjs.com}"
REGISTRY_URL="$(oc_ask "Public registry URL clients will use" "$DEFAULT_REG_URL")"

# 5. .env (only if absent - never clobber operator customization)
if [ ! -f "$APP_DIR/.env" ]; then
    ADMIN_KEY="$(oc_gen_secret)"
    cat > "$APP_DIR/.env" <<ENVEOF
# Obscura47 Registry + Exit configuration (generated by vps-setup.sh)
OBSCURA_REGISTRY_URL=${REGISTRY_URL}
OBSCURA_REGISTRY_PORT=${REGISTRY_PORT}
OBSCURA_REGISTRY_ADMIN_KEY=${ADMIN_KEY}

# Exit node
OBSCURA_EXIT_LISTEN_PORT=${EXIT_PORT}
OBSCURA_EXIT_WS_PORT=${EXIT_WS_PORT}

# Relay node: DISABLED here. This box is registry + exit only; run the relay on
# a dedicated host (scripts/vps-node-setup.sh). Advertising the exit IP as a
# relay hop lets circuit builders consume it as a middle node instead of as the
# exit, starving exit selection and breaking clearnet/.obscura egress.
OBSCURA_RUN_NODE=false
OBSCURA_NODE_LISTEN_PORT=5001
OBSCURA_NODE_WS_PORT=5002

# Security
OBSCURA_EXIT_DENY_PRIVATE_IPS=true

# Audit
OBSCURA_EXIT_EGRESS_AUDIT_ENABLED=true
OBSCURA_AUDIT_RETENTION_DAYS=14

# Writable paths (must stay under ${DATA_DIR} for the hardened unit's ReadWritePaths)
OBSCURA_REGISTRY_DB_PATH=${DATA_DIR}/registry.db
OBSCURA_EXIT_KEY_PATH=${DATA_DIR}/exit_key.pem
OBSCURA_NODE_KEY_PATH=${DATA_DIR}/node_key.pem
OBSCURA_AUDIT_LOG_DIR=${DATA_DIR}/audit
OBSCURA_LOG_DIR=${DATA_DIR}/logs

# TLS is terminated by nginx (see scripts/nginx/). Uncomment to let the app
# serve TLS directly instead:
# OBSCURA_REGISTRY_TLS_CERT=/etc/letsencrypt/live/<host>/fullchain.pem
# OBSCURA_REGISTRY_TLS_KEY=/etc/letsencrypt/live/<host>/privkey.pem
ENVEOF
    chown "$RUN_USER:$RUN_GROUP" "$APP_DIR/.env"
    chmod 600 "$APP_DIR/.env"
    oc_log "Created .env with an auto-generated admin key (no manual editing needed)"
else
    oc_step ".env already exists - leaving it untouched"
fi

# 6. systemd unit (rendered for this checkout)
oc_render_unit "$APP_DIR/scripts/obscura47-server.service.template" \
    "obscura47-server.service" "$APP_DIR" "$RUN_USER" "$RUN_GROUP" "$DATA_DIR" "server.py"
systemctl enable obscura47-server >/dev/null 2>&1 || true

# 7. firewall (registry + exit; node ports intentionally NOT opened here)
if oc_confirm "Open firewall for registry($REGISTRY_PORT) + exit($EXIT_PORT,$EXIT_WS_PORT)?"; then
    oc_open_firewall "$REGISTRY_PORT" "$EXIT_PORT" "$EXIT_WS_PORT" || true
    oc_step "Note: if nginx fronts the registry on 443, ensure 443/tcp is open too."
fi

# 8. start + verify
oc_step "Starting obscura47-server..."
systemctl restart obscura47-server
sleep 3
if systemctl is-active --quiet obscura47-server; then
    oc_log "Service is active"
else
    oc_err "Service failed to start - check: journalctl -u obscura47-server -e"
fi
oc_verify "$APP_DIR" "exit" "$EXIT_WS_PORT"

echo
echo "=== Setup complete ==="
echo "  Service: systemctl status obscura47-server   Logs: journalctl -u obscura47-server -f"
echo "  Config:  $APP_DIR/.env   (admin key was auto-generated)"
echo "  Relay node is OFF here - set up a dedicated node with scripts/vps-node-setup.sh"
echo
